// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqGSTUeQqzQeuiUTve4rdHFsiktmrAkMA',
    appId: '1:543252902851:web:452951f32e8d4316eec376',
    messagingSenderId: '543252902851',
    projectId: 'minilaw-2088a',
    authDomain: 'minilaw-2088a.firebaseapp.com',
    storageBucket: 'minilaw-2088a.appspot.com',
    measurementId: 'G-JM2K7Y44GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2H384IIjcgIAYdeoOmtJXliVul1Qm90',
    appId: '1:543252902851:android:ff4fb92cd6b11944eec376',
    messagingSenderId: '543252902851',
    projectId: 'minilaw-2088a',
    storageBucket: 'minilaw-2088a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6Yi7XBnTvwnQrwHLwh-49QRVh-GJAik',
    appId: '1:543252902851:ios:aae69ba0fc936d6eeec376',
    messagingSenderId: '543252902851',
    projectId: 'minilaw-2088a',
    storageBucket: 'minilaw-2088a.appspot.com',
    iosBundleId: 'com.krisha.minilaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6Yi7XBnTvwnQrwHLwh-49QRVh-GJAik',
    appId: '1:543252902851:ios:eebf6f10dca273e0eec376',
    messagingSenderId: '543252902851',
    projectId: 'minilaw-2088a',
    storageBucket: 'minilaw-2088a.appspot.com',
    iosBundleId: 'com.krisha.minilaw.RunnerTests',
  );
}
